### ISSUE TITLE
Error on Get JSON Data

### ISSUE THREAD

**Issue by yFonteSeca** [nat236919/Covid2019API#8] opened 2020-02-14 18:08 UTC
Error on jSON pages
"Internal Server Error"

**Comment by georgecode** [comment] 2020-02-14 22:04
I'm having the same issue domain is up but all the paths give 500 Error
Seems to be caused by most recent commit worked yesterday

I'm not too familiar with python, but it looks like a problem is in app/models/covid_model.py  line 11
It seems to be trying to importing helper.py form app/models/utils
when it should be importing from app/utils

Great API by the way, saved a ton of time I would have wasted processing the csv files.

**Comment by nat236919** [comment] 2020-02-15 01:13
There are major changes from the source; therefore, it indicated an error. I have just committed https://github.com/nat236919/Covid2019API/commit/24a3747b4879f6f5956706e53eced23490e73601. This should fix the problem.

**Closed** 2020-02-15 06:22 UTC
Labels: bug
